### ISSUE TITLE
Update `actions/upload-artifact` to v4 in `reusable_build.yml`

### ISSUE THREAD

**Issue by aido** [LedgerHQ/ledger-app-workflows#78]
Hi,

Building an application using the reusable workflow `LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1` gives the following warning:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

The offending line is possibly this one:

https://github.com/LedgerHQ/ledger-app-workflows/blob/085925a3f91ebd51eb4973a86c5338a2c0d82c5d/.github/workflows/reusable_build.yml#L120

`actions/upload-artifact@v3` is used in several workflows and all instances should probably be updated to v4

**Comment by tdejoigny-ledger** [comment]
cc: @fbeutin-ledger

**Comment by fbeutin-ledger** [comment]
https://github.com/LedgerHQ/ledger-app-workflows/pull/79
